create table if not exists public.device_happy_hour_overrides (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  device_id text not null references public.devices(device_id) on delete cascade,
  amount_total numeric not null default 0 check (amount_total > 0),
  amount_remaining numeric not null default 0 check (amount_remaining >= 0),
  status text not null default 'active' check (status = any (array['active'::text, 'completed'::text, 'cancelled'::text])),
  completed_at timestamp with time zone,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.device_happy_hour_override_wins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  override_id bigint not null references public.device_happy_hour_overrides(id) on delete cascade,
  device_id text not null references public.devices(device_id) on delete cascade,
  spin_key text,
  event_ts timestamp with time zone not null default now(),
  runtime_mode text not null check (runtime_mode = any (array['BASE'::text, 'HAPPY'::text])),
  requested_amount numeric not null check (requested_amount >= 0),
  accepted_amount numeric not null check (accepted_amount >= 0),
  normal_win_cap_amount numeric not null check (normal_win_cap_amount >= 0),
  override_paid_amount numeric not null check (override_paid_amount >= 0),
  override_remaining_after numeric not null check (override_remaining_after >= 0),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_device_happy_hour_overrides_active_device
  on public.device_happy_hour_overrides (device_id, status, created_at desc);

create index if not exists idx_device_happy_hour_override_wins_device_time
  on public.device_happy_hour_override_wins (device_id, event_ts desc);

create or replace function public.enqueue_device_happy_hour_override(p_device_id text, p_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.devices%rowtype;
  v_amount numeric := round(greatest(coalesce(p_amount, 0), 0), 4);
  v_actor_user_id uuid := auth.uid();
  v_actor_email text := null;
  v_actor_full_name text := null;
  v_override public.device_happy_hour_overrides%rowtype;
begin
  if trim(coalesce(p_device_id, '')) = '' then
    raise exception 'p_device_id is required';
  end if;

  if v_amount <= 0 then
    raise exception 'p_amount must be greater than 0';
  end if;

  select *
  into v_device
  from public.devices
  where device_id = trim(p_device_id)
  for update;

  if not found then
    raise exception 'Device not found: %', p_device_id;
  end if;

  if coalesce(v_device.is_free_game, false)
     or coalesce(v_device.pending_free_spins, 0) > 0
     or coalesce(v_device.show_free_spin_intro, false) then
    raise exception 'Device % is currently in a free-spin flow; wait until it finishes before overriding happy hour', p_device_id;
  end if;

  if exists (
    select 1
    from public.device_happy_hour_overrides o
    where o.device_id = v_device.device_id
      and o.status = 'active'
      and o.amount_remaining > 0
  ) then
    raise exception 'Device % already has an active happy hour override', v_device.device_id;
  end if;

  if v_actor_user_id is not null then
    select du.email, du.full_name
    into v_actor_email, v_actor_full_name
    from public.dashboard_users du
    where du.user_id = v_actor_user_id;
  end if;

  insert into public.device_happy_hour_overrides (
    device_id,
    amount_total,
    amount_remaining,
    status,
    metadata
  )
  values (
    v_device.device_id,
    v_amount,
    v_amount,
    'active',
    jsonb_build_object(
      'source', 'dashboard_device_happy_override',
      'deviceId', v_device.device_id,
      'deviceName', coalesce(v_device.name, ''),
      'actor_user_id', v_actor_user_id,
      'actor_email', v_actor_email,
      'actor_full_name', v_actor_full_name,
      'createdAt', now()
    )
  )
  returning * into v_override;

  return jsonb_build_object(
    'ok', true,
    'id', v_override.id,
    'device_id', v_override.device_id,
    'amount_total', v_override.amount_total,
    'amount_remaining', v_override.amount_remaining,
    'status', v_override.status
  );
end;
$$;

create or replace function public.apply_metric_event(
  p_device_id text,
  p_event_type text,
  p_amount numeric,
  p_event_ts timestamp with time zone default now(),
  p_metadata jsonb default '{}'::jsonb,
  p_write_ledger boolean default true
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_ts timestamptz := coalesce(p_event_ts, now());
  v_date date := coalesce((v_event_ts at time zone 'utc')::date, (now() at time zone 'utc')::date);
  v_event text := lower(trim(coalesce(p_event_type, '')));
  v_amt numeric := greatest(coalesce(p_amount, 0), 0);
  v_balance_delta numeric := 0;
  v_coins_in numeric := 0;
  v_hopper_in numeric := 0;
  v_hopper_out numeric := 0;
  v_bet numeric := 0;
  v_win numeric := 0;
  v_withdraw numeric := 0;
  v_spins bigint := 0;
  v_house_take numeric := 0;
  v_pool_contrib numeric := 0;
  v_pool_paid numeric := 0;
  v_jackpot_contrib numeric := 0;
  v_jackpot_paid numeric := 0;
  v_spin_win_hint numeric := 0;
  v_effective_spin_win_hint numeric := 0;
  v_requested_win numeric := 0;
  v_last_bet_amount numeric := null;
  v_last_bet_at timestamptz := null;
  v_runtime public.casino_runtime;
  v_profile_id text;
  v_profile_house_pct numeric := 0;
  v_profile_jackpot_pct numeric := 0;
  v_house_pct numeric := 0;
  v_jackpot_pct numeric := 0;
  v_happy_pct numeric := 0;
  v_house_target numeric := 0;
  v_jackpot_target numeric := 0;
  v_after_house numeric := 0;
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_max_win_cap numeric := null;
  v_normal_win_cap numeric := null;
  v_total_win_cap numeric := null;
  v_over_cap_amount numeric := 0;
  v_spin_key text := nullif(trim(coalesce(p_metadata->>'spinKey', '')), '');
  v_guard_funding_source text := 'runtime_pool';
  v_guarded_from_spin boolean := false;
  v_dedup_inserted_count integer := 0;
  v_deployment_mode text := 'online';
  v_effective_device_status text := 'offline';
  v_counts_toward_global boolean := false;
  v_spin_is_free_game boolean := false;
  v_device_happy_override public.device_happy_hour_overrides%rowtype;
  v_device_happy_override_active boolean := false;
  v_device_happy_override_cap numeric := 0;
  v_base_win_amount numeric := 0;
  v_override_win_amount numeric := 0;
begin
  if p_device_id is null or trim(p_device_id) = '' then
    raise exception 'p_device_id is required';
  end if;

  if v_amt = 0 and v_event not in ('spin') then
    return;
  end if;

  insert into public.devices (device_id)
  values (p_device_id)
  on conflict (device_id) do nothing;

  select
    coalesce(nullif(trim(d.deployment_mode), ''), 'online'),
    public.resolve_device_presence_status(d.device_status, d.last_seen_at, v_event_ts),
    public.should_count_device_activity(d.deployment_mode, d.device_status, d.last_seen_at, v_event_ts)
  into v_deployment_mode, v_effective_device_status, v_counts_toward_global
  from public.devices d
  where d.device_id = p_device_id;

  if v_metadata ? 'isFreeGame' then
    begin
      v_spin_is_free_game := coalesce((v_metadata->>'isFreeGame')::boolean, false);
    exception when others then
      v_spin_is_free_game := false;
    end;
  end if;

  if v_spin_key is not null and v_event in ('bet', 'win', 'spin') then
    insert into public.device_spin_event_dedup (
      device_id,
      spin_key,
      event_type,
      event_ts,
      amount,
      metadata
    )
    values (
      p_device_id,
      v_spin_key,
      v_event,
      v_event_ts,
      v_amt,
      v_metadata
    )
    on conflict (device_id, spin_key, event_type) do nothing;

    get diagnostics v_dedup_inserted_count = row_count;

    if v_dedup_inserted_count = 0 then
      return;
    end if;
  end if;

  if v_event = 'coins_in' then
    if coalesce(v_metadata->>'source', '') <> 'coin_acceptor' then
      return;
    end if;

    v_coins_in := v_amt;
    v_balance_delta := v_amt;
  elsif v_event = 'hopper_in' then
    v_hopper_in := v_amt;
  elsif v_event = 'withdrawal' then
    v_hopper_out := v_amt;
    v_withdraw := v_amt;
    v_balance_delta := -v_amt;
  end if;

  if v_event in ('coins_in', 'hopper_in', 'withdrawal') then
    update public.devices
    set
      balance = greatest(0, balance + v_balance_delta),
      coins_in_total = coins_in_total + v_coins_in,
      hopper_balance = greatest(0, hopper_balance + v_hopper_in - v_hopper_out),
      hopper_in_total = hopper_in_total + v_hopper_in,
      hopper_out_total = hopper_out_total + v_hopper_out,
      withdraw_total = withdraw_total + v_withdraw,
      updated_at = now()
    where device_id = p_device_id;

    insert into public.device_daily_stats (
      stat_date,
      device_id,
      coins_in_amount,
      hopper_in_amount,
      hopper_out_amount,
      bet_amount,
      win_amount,
      house_take_amount,
      jackpot_contrib_amount,
      jackpot_win_amount,
      withdrawal_amount,
      balance_change,
      event_count,
      spins_count,
      prize_pool_contrib_amount,
      prize_pool_paid_amount,
      included_coins_in_amount,
      included_hopper_in_amount,
      included_hopper_out_amount,
      included_bet_amount,
      included_win_amount,
      included_house_take_amount,
      included_jackpot_contrib_amount,
      included_jackpot_win_amount,
      included_withdrawal_amount,
      included_balance_change,
      included_event_count,
      included_spins_count,
      included_prize_pool_contrib_amount,
      included_prize_pool_paid_amount,
      updated_at
    )
    values (
      v_date,
      p_device_id,
      v_coins_in,
      v_hopper_in,
      v_hopper_out,
      0,
      0,
      0,
      0,
      0,
      v_withdraw,
      v_balance_delta,
      1,
      0,
      0,
      0,
      case when v_counts_toward_global then v_coins_in else 0 end,
      case when v_counts_toward_global then v_hopper_in else 0 end,
      case when v_counts_toward_global then v_hopper_out else 0 end,
      0,
      0,
      0,
      0,
      0,
      case when v_counts_toward_global then v_withdraw else 0 end,
      case when v_counts_toward_global then v_balance_delta else 0 end,
      case when v_counts_toward_global then 1 else 0 end,
      0,
      0,
      0,
      now()
    )
    on conflict (stat_date, device_id) do update
    set
      coins_in_amount = device_daily_stats.coins_in_amount + excluded.coins_in_amount,
      hopper_in_amount = device_daily_stats.hopper_in_amount + excluded.hopper_in_amount,
      hopper_out_amount = device_daily_stats.hopper_out_amount + excluded.hopper_out_amount,
      withdrawal_amount = device_daily_stats.withdrawal_amount + excluded.withdrawal_amount,
      balance_change = device_daily_stats.balance_change + excluded.balance_change,
      event_count = device_daily_stats.event_count + 1,
      included_coins_in_amount = device_daily_stats.included_coins_in_amount + excluded.included_coins_in_amount,
      included_hopper_in_amount = device_daily_stats.included_hopper_in_amount + excluded.included_hopper_in_amount,
      included_hopper_out_amount = device_daily_stats.included_hopper_out_amount + excluded.included_hopper_out_amount,
      included_withdrawal_amount = device_daily_stats.included_withdrawal_amount + excluded.included_withdrawal_amount,
      included_balance_change = device_daily_stats.included_balance_change + excluded.included_balance_change,
      included_event_count = device_daily_stats.included_event_count + excluded.included_event_count,
      updated_at = now();

    if p_write_ledger then
      insert into public.device_metric_events (
        event_ts,
        device_id,
        event_type,
        amount,
        metadata,
        deployment_mode,
        device_status,
        counts_toward_global
      )
      values (
        v_event_ts,
        p_device_id,
        v_event,
        v_amt,
        v_metadata,
        v_deployment_mode,
        v_effective_device_status,
        v_counts_toward_global
      );
    end if;

    return;
  end if;

  insert into public.casino_runtime (id, base_profile_id, happy_profile_id)
  values (true, 'base_slow', 'happy_slow')
  on conflict (id) do nothing;

  select * into v_runtime
  from public.casino_runtime
  where id = true
  for update;

  select *
  into v_device_happy_override
  from public.device_happy_hour_overrides o
  where o.device_id = p_device_id
    and o.status = 'active'
    and o.amount_remaining > 0
  order by o.created_at desc, o.id desc
  limit 1
  for update;

  v_device_happy_override_active :=
    found
    and greatest(coalesce(v_device_happy_override.amount_remaining, 0), 0) > 0
    and v_runtime.active_mode <> 'HAPPY';

  v_device_happy_override_cap := case
    when v_device_happy_override_active then greatest(coalesce(v_device_happy_override.amount_remaining, 0), 0)
    else 0
  end;

  if coalesce(v_runtime.max_win_enabled, true) then
    select public.compute_max_win_cap(d.last_bet_amount)
      into v_max_win_cap
    from public.devices d
    where d.device_id = p_device_id;
  end if;

  if v_event = 'bet' then
    v_bet := v_amt;
    v_balance_delta := -v_amt;
    v_last_bet_amount := v_bet;
    v_last_bet_at := v_event_ts;
  elsif v_event = 'spin' then
    v_spins := 1;
    v_last_bet_at := v_event_ts;

    if not coalesce(v_spin_is_free_game, false) then
      v_bet := v_amt;
      v_balance_delta := -v_amt;
      v_last_bet_amount := v_bet;

      v_profile_id := case
        when v_runtime.active_mode = 'HAPPY' or v_device_happy_override_active then v_runtime.happy_profile_id
        else v_runtime.base_profile_id
      end;

      select
        coalesce(house_pct, 0),
        coalesce(pool_pct, 0)
      into v_profile_house_pct, v_profile_jackpot_pct
      from public.rtp_profiles
      where id = v_profile_id;

      v_house_pct := greatest(v_profile_house_pct, 0);
      v_jackpot_pct := greatest(v_profile_jackpot_pct, 0);
      v_jackpot_pct := least(v_jackpot_pct, greatest(100 - v_house_pct, 0));
      v_happy_pct := greatest(100 - v_house_pct - v_jackpot_pct, 0);

      v_house_target := v_bet * v_house_pct / 100.0;
      v_jackpot_target := v_bet * v_jackpot_pct / 100.0;

      v_house_take := greatest(v_house_target, 0);
      v_after_house := v_bet - v_house_take;
      v_jackpot_contrib := greatest(least(v_jackpot_target, v_after_house), 0);
      v_pool_contrib := greatest(v_after_house - v_jackpot_contrib, 0);

      if v_runtime.active_mode = 'HAPPY' then
        v_guard_funding_source := 'happy_prize_pool';
      elsif v_device_happy_override_active then
        v_guard_funding_source := 'device_happy_override';
      else
        v_guard_funding_source := 'base_prize_pool';
      end if;

      if v_metadata ? 'totalWin' then
        begin
          v_spin_win_hint := greatest(coalesce((v_metadata->>'totalWin')::numeric, 0), 0);
        exception when others then
          v_spin_win_hint := 0;
        end;
      end if;

      if v_runtime.active_mode = 'HAPPY' then
        v_normal_win_cap := greatest(coalesce(v_runtime.happy_hour_prize_balance, 0), 0);
      elsif v_device_happy_override_active then
        v_normal_win_cap := 0;
      else
        v_normal_win_cap := greatest(coalesce(v_runtime.prize_pool_balance, 0), 0) + v_pool_contrib;
      end if;

      v_total_win_cap := greatest(coalesce(v_normal_win_cap, 0), 0) + greatest(coalesce(v_device_happy_override_cap, 0), 0);

      if v_max_win_cap is not null then
        v_total_win_cap := least(v_total_win_cap, v_max_win_cap);
      end if;

      v_normal_win_cap := greatest(coalesce(v_normal_win_cap, 0), 0);
      v_total_win_cap := greatest(coalesce(v_total_win_cap, 0), 0);
      v_effective_spin_win_hint := least(v_spin_win_hint, v_total_win_cap);

      v_metadata := v_metadata || jsonb_build_object(
        'requestedTotalWin', v_spin_win_hint,
        'effectiveTotalWinHint', v_effective_spin_win_hint,
        'normalWinFundingCap', v_normal_win_cap,
        'happyOverrideFundingCap', v_device_happy_override_cap,
        'totalWinFundingCap', v_total_win_cap,
        'deviceHappyOverrideActive', v_device_happy_override_active,
        'deviceHappyOverrideId', case when v_device_happy_override_active then v_device_happy_override.id else null end,
        'winFundingSource', v_guard_funding_source,
        'overCapWinHint', v_spin_win_hint > v_effective_spin_win_hint + 0.0001
      );
    end if;

    if v_counts_toward_global then
      update public.casino_runtime
      set
        prize_pool_balance = greatest(0, prize_pool_balance + v_pool_contrib),
        jackpot_pool_balance = greatest(0, jackpot_pool_balance + v_jackpot_contrib),
        happy_pool_spin_counter = happy_pool_spin_counter + v_spins,
        jackpot_pool_spin_counter = jackpot_pool_spin_counter + v_spins,
        updated_at = now()
      where id = true
      returning * into v_runtime;

      perform public.process_pool_goal_queues(v_event_ts);
      perform public.trigger_jackpot_payout_if_ready(v_event_ts);

      v_jackpot_paid := public.process_device_jackpot_payout(
        p_device_id,
        v_event_ts,
        v_spin_is_free_game
      );

      if v_jackpot_paid > 0 then
        v_win := v_win + v_jackpot_paid;
        v_balance_delta := v_balance_delta + v_jackpot_paid;
        v_metadata := v_metadata || jsonb_build_object(
          'jackpotPayout', v_jackpot_paid,
          'jackpotCampaignPayout', true
        );
      end if;
    else
      v_jackpot_paid := public.process_device_jackpot_payout(
        p_device_id,
        v_event_ts,
        v_spin_is_free_game
      );

      if v_jackpot_paid > 0 then
        v_win := v_win + v_jackpot_paid;
        v_balance_delta := v_balance_delta + v_jackpot_paid;
        v_metadata := v_metadata || jsonb_build_object(
          'jackpotPayout', v_jackpot_paid,
          'jackpotCampaignPayout', true,
          'excludedFromGlobal', true
        );
      end if;
    end if;
  elsif v_event = 'win' then
    v_requested_win := v_amt;

    if not v_counts_toward_global then
      v_win := v_requested_win;
      v_pool_paid := v_requested_win;
      v_balance_delta := v_requested_win;
      v_metadata := v_metadata || jsonb_build_object(
        'requestedWin', v_requested_win,
        'acceptedWin', v_requested_win,
        'excludedFromGlobal', true
      );
    else
      if v_spin_key is not null then
        begin
          select
            greatest(coalesce((e.metadata->>'normalWinFundingCap')::numeric, 0), 0),
            greatest(coalesce((e.metadata->>'happyOverrideFundingCap')::numeric, 0), 0),
            coalesce(e.metadata->>'winFundingSource', 'runtime_pool')
          into v_normal_win_cap, v_device_happy_override_cap, v_guard_funding_source
          from public.device_metric_events e
          where e.device_id = p_device_id
            and e.event_type = 'spin'
            and coalesce(e.metadata->>'spinKey', '') = v_spin_key
          order by e.event_ts desc, e.id desc
          limit 1;

          v_guarded_from_spin := v_normal_win_cap is not null;
        exception when others then
          v_normal_win_cap := null;
          v_guarded_from_spin := false;
        end;

        if not v_guarded_from_spin then
          v_normal_win_cap := null;
          v_device_happy_override_cap := case
            when v_device_happy_override_active then greatest(coalesce(v_device_happy_override.amount_remaining, 0), 0)
            else 0
          end;
          v_guard_funding_source := case
            when v_runtime.active_mode = 'HAPPY' then 'happy_prize_pool'
            when v_device_happy_override_active and v_device_happy_override_cap > 0 then 'device_happy_override'
            else 'base_prize_pool'
          end;
        end if;
      end if;

      if v_normal_win_cap is null then
        if v_runtime.active_mode = 'HAPPY' then
          v_normal_win_cap := greatest(coalesce(v_runtime.happy_hour_prize_balance, 0), 0);
          v_guard_funding_source := 'happy_prize_pool';
        else
          v_device_happy_override_cap := greatest(coalesce(v_device_happy_override_cap, 0), 0);
          if v_device_happy_override_active and v_device_happy_override_cap > 0 then
            v_normal_win_cap := 0;
            v_guard_funding_source := 'device_happy_override';
          else
            v_normal_win_cap := greatest(coalesce(v_runtime.prize_pool_balance, 0), 0);
            v_guard_funding_source := 'base_prize_pool';
          end if;
        end if;
      end if;

      v_total_win_cap := greatest(coalesce(v_normal_win_cap, 0), 0) + greatest(coalesce(v_device_happy_override_cap, 0), 0);

      if v_max_win_cap is not null then
        v_total_win_cap := least(greatest(coalesce(v_total_win_cap, 0), 0), v_max_win_cap);
      end if;

      v_normal_win_cap := greatest(coalesce(v_normal_win_cap, 0), 0);
      v_total_win_cap := greatest(coalesce(v_total_win_cap, 0), 0);
      v_win := least(v_requested_win, v_total_win_cap);
      v_over_cap_amount := greatest(v_requested_win - v_win, 0);

      if v_over_cap_amount > 0.0001 then
        insert into public.over_cap_win_events (
          device_id,
          spin_key,
          event_ts,
          runtime_mode,
          funding_source,
          requested_amount,
          accepted_amount,
          funding_cap_amount,
          over_amount,
          metadata
        )
        values (
          p_device_id,
          v_spin_key,
          v_event_ts,
          v_runtime.active_mode,
          v_guard_funding_source,
          v_requested_win,
          v_win,
          v_total_win_cap,
          v_over_cap_amount,
          v_metadata
        );
      end if;

      v_metadata := v_metadata || jsonb_build_object(
        'requestedWin', v_requested_win,
        'acceptedWin', v_win,
        'normalWinFundingCap', v_normal_win_cap,
        'happyOverrideFundingCap', v_device_happy_override_cap,
        'totalWinFundingCap', v_total_win_cap,
        'winFundingSource', v_guard_funding_source,
        'overCapWinAdjusted', v_over_cap_amount > 0.0001
      );

      v_balance_delta := v_win;

      if v_runtime.active_mode = 'HAPPY' then
        v_pool_paid := v_win;

        update public.casino_runtime
        set
          happy_hour_prize_balance = greatest(0, happy_hour_prize_balance - v_pool_paid),
          updated_at = now()
        where id = true
        returning * into v_runtime;

        if v_runtime.active_happy_pot_id is not null then
          update public.happy_hour_pots
          set amount_remaining = greatest(amount_remaining - v_pool_paid, 0)
          where id = v_runtime.active_happy_pot_id;
        end if;
      else
        if v_device_happy_override_active and v_guard_funding_source = 'device_happy_override' then
          v_base_win_amount := 0;
          v_override_win_amount := v_win;
          v_pool_paid := 0;
        else
          v_base_win_amount := least(v_win, v_normal_win_cap);
          v_override_win_amount := greatest(v_win - v_base_win_amount, 0);
          v_pool_paid := v_win;
        end if;

        if v_base_win_amount > 0 then
          update public.casino_runtime
          set
            prize_pool_balance = greatest(0, prize_pool_balance - v_base_win_amount),
            updated_at = now()
          where id = true
          returning * into v_runtime;
        end if;

        if v_override_win_amount > 0 and v_device_happy_override_active then
          update public.device_happy_hour_overrides
          set
            amount_remaining = greatest(0, amount_remaining - v_override_win_amount),
            status = case
              when greatest(0, amount_remaining - v_override_win_amount) <= 0 then 'completed'
              else status
            end,
            completed_at = case
              when greatest(0, amount_remaining - v_override_win_amount) <= 0 then coalesce(completed_at, v_event_ts)
              else completed_at
            end,
            updated_at = now()
          where id = v_device_happy_override.id
          returning * into v_device_happy_override;

          insert into public.device_happy_hour_override_wins (
            override_id,
            device_id,
            spin_key,
            event_ts,
            runtime_mode,
            requested_amount,
            accepted_amount,
            normal_win_cap_amount,
            override_paid_amount,
            override_remaining_after,
            metadata
          )
          values (
            v_device_happy_override.id,
            p_device_id,
            v_spin_key,
            v_event_ts,
            v_runtime.active_mode,
            v_requested_win,
            v_win,
            v_normal_win_cap,
            v_override_win_amount,
            greatest(coalesce(v_device_happy_override.amount_remaining, 0), 0),
            v_metadata || jsonb_build_object(
              'deviceHappyOverrideId', v_device_happy_override.id,
              'baseWinAmount', v_base_win_amount,
              'overrideWinAmount', v_override_win_amount
            )
          );
        end if;

        v_metadata := v_metadata || jsonb_build_object(
          'baseWinAmount', v_base_win_amount,
          'overrideWinAmount', v_override_win_amount,
          'deviceHappyOverrideApplied', v_override_win_amount > 0.0001,
          'deviceHappyOverrideId', case when v_override_win_amount > 0.0001 then v_device_happy_override.id else null end,
          'deviceHappyOverrideRemainingAfter', case
            when v_override_win_amount > 0.0001 then greatest(coalesce(v_device_happy_override.amount_remaining, 0), 0)
            else null
          end
        );
      end if;
    end if;
  else
    raise exception 'unsupported metric event type: %', p_event_type;
  end if;

  if v_event in ('spin', 'win') and v_counts_toward_global then
    perform public.recompute_casino_mode();
  end if;

  update public.devices
  set
    balance = greatest(0, balance + v_balance_delta),
    coins_in_total = coins_in_total + v_coins_in,
    hopper_balance = greatest(0, hopper_balance + v_hopper_in - v_hopper_out),
    hopper_in_total = hopper_in_total + v_hopper_in,
    hopper_out_total = hopper_out_total + v_hopper_out,
    bet_total = bet_total + v_bet,
    win_total = win_total + v_win,
    house_take_total = house_take_total + v_house_take,
    jackpot_contrib_total = jackpot_contrib_total + v_jackpot_contrib,
    jackpot_win_total = jackpot_win_total + v_jackpot_paid,
    last_bet_amount = coalesce(v_last_bet_amount, last_bet_amount),
    last_bet_at = coalesce(v_last_bet_at, last_bet_at),
    withdraw_total = withdraw_total + v_withdraw,
    spins_total = spins_total + v_spins,
    prize_pool_contrib_total = prize_pool_contrib_total + v_pool_contrib,
    prize_pool_paid_total = prize_pool_paid_total + v_pool_paid,
    updated_at = now()
  where device_id = p_device_id;

  insert into public.device_daily_stats (
    stat_date,
    device_id,
    coins_in_amount,
    hopper_in_amount,
    hopper_out_amount,
    bet_amount,
    win_amount,
    house_take_amount,
    jackpot_contrib_amount,
    jackpot_win_amount,
    withdrawal_amount,
    balance_change,
    event_count,
    spins_count,
    prize_pool_contrib_amount,
    prize_pool_paid_amount,
    included_coins_in_amount,
    included_hopper_in_amount,
    included_hopper_out_amount,
    included_bet_amount,
    included_win_amount,
    included_house_take_amount,
    included_jackpot_contrib_amount,
    included_jackpot_win_amount,
    included_withdrawal_amount,
    included_balance_change,
    included_event_count,
    included_spins_count,
    included_prize_pool_contrib_amount,
    included_prize_pool_paid_amount,
    updated_at
  )
  values (
    v_date,
    p_device_id,
    v_coins_in,
    v_hopper_in,
    v_hopper_out,
    v_bet,
    v_win,
    v_house_take,
    v_jackpot_contrib,
    v_jackpot_paid,
    v_withdraw,
    v_balance_delta,
    1,
    v_spins,
    v_pool_contrib,
    v_pool_paid,
    case when v_counts_toward_global then v_coins_in else 0 end,
    case when v_counts_toward_global then v_hopper_in else 0 end,
    case when v_counts_toward_global then v_hopper_out else 0 end,
    case when v_counts_toward_global then v_bet else 0 end,
    case when v_counts_toward_global then v_win else 0 end,
    case when v_counts_toward_global then v_house_take else 0 end,
    case when v_counts_toward_global then v_jackpot_contrib else 0 end,
    case when v_counts_toward_global then v_jackpot_paid else 0 end,
    case when v_counts_toward_global then v_withdraw else 0 end,
    case when v_counts_toward_global then v_balance_delta else 0 end,
    case when v_counts_toward_global then 1 else 0 end,
    case when v_counts_toward_global then v_spins else 0 end,
    case when v_counts_toward_global then v_pool_contrib else 0 end,
    case when v_counts_toward_global then v_pool_paid else 0 end,
    now()
  )
  on conflict (stat_date, device_id) do update
  set
    coins_in_amount = device_daily_stats.coins_in_amount + excluded.coins_in_amount,
    hopper_in_amount = device_daily_stats.hopper_in_amount + excluded.hopper_in_amount,
    hopper_out_amount = device_daily_stats.hopper_out_amount + excluded.hopper_out_amount,
    bet_amount = device_daily_stats.bet_amount + excluded.bet_amount,
    win_amount = device_daily_stats.win_amount + excluded.win_amount,
    house_take_amount = device_daily_stats.house_take_amount + excluded.house_take_amount,
    jackpot_contrib_amount = device_daily_stats.jackpot_contrib_amount + excluded.jackpot_contrib_amount,
    jackpot_win_amount = device_daily_stats.jackpot_win_amount + excluded.jackpot_win_amount,
    withdrawal_amount = device_daily_stats.withdrawal_amount + excluded.withdrawal_amount,
    balance_change = device_daily_stats.balance_change + excluded.balance_change,
    event_count = device_daily_stats.event_count + 1,
    spins_count = device_daily_stats.spins_count + excluded.spins_count,
    prize_pool_contrib_amount = device_daily_stats.prize_pool_contrib_amount + excluded.prize_pool_contrib_amount,
    prize_pool_paid_amount = device_daily_stats.prize_pool_paid_amount + excluded.prize_pool_paid_amount,
    included_coins_in_amount = device_daily_stats.included_coins_in_amount + excluded.included_coins_in_amount,
    included_hopper_in_amount = device_daily_stats.included_hopper_in_amount + excluded.included_hopper_in_amount,
    included_hopper_out_amount = device_daily_stats.included_hopper_out_amount + excluded.included_hopper_out_amount,
    included_bet_amount = device_daily_stats.included_bet_amount + excluded.included_bet_amount,
    included_win_amount = device_daily_stats.included_win_amount + excluded.included_win_amount,
    included_house_take_amount = device_daily_stats.included_house_take_amount + excluded.included_house_take_amount,
    included_jackpot_contrib_amount = device_daily_stats.included_jackpot_contrib_amount + excluded.included_jackpot_contrib_amount,
    included_jackpot_win_amount = device_daily_stats.included_jackpot_win_amount + excluded.included_jackpot_win_amount,
    included_withdrawal_amount = device_daily_stats.included_withdrawal_amount + excluded.included_withdrawal_amount,
    included_balance_change = device_daily_stats.included_balance_change + excluded.included_balance_change,
    included_event_count = device_daily_stats.included_event_count + excluded.included_event_count,
    included_spins_count = device_daily_stats.included_spins_count + excluded.included_spins_count,
    included_prize_pool_contrib_amount = device_daily_stats.included_prize_pool_contrib_amount + excluded.included_prize_pool_contrib_amount,
    included_prize_pool_paid_amount = device_daily_stats.included_prize_pool_paid_amount + excluded.included_prize_pool_paid_amount,
    updated_at = now();

  if p_write_ledger then
    insert into public.device_metric_events (
      event_ts,
      device_id,
      event_type,
      amount,
      metadata,
      deployment_mode,
      device_status,
      counts_toward_global
    )
    values (
      v_event_ts,
      p_device_id,
      v_event,
      case
        when v_event = 'win' then v_win
        when v_event = 'spin' then v_amt
        when v_event = 'coins_in' then v_coins_in
        when v_event = 'hopper_in' then v_hopper_in
        when v_event = 'withdrawal' then v_withdraw
        when v_event = 'bet' then v_bet
        else v_amt
      end,
      v_metadata,
      v_deployment_mode,
      v_effective_device_status,
      v_counts_toward_global
    );

    if v_event = 'spin' and v_jackpot_paid > 0 then
      insert into public.device_metric_events (
        event_ts,
        device_id,
        event_type,
        amount,
        metadata,
        deployment_mode,
        device_status,
        counts_toward_global
      )
      values (
        v_event_ts,
        p_device_id,
        'win',
        v_jackpot_paid,
        v_metadata || jsonb_build_object(
          'acceptedWin', v_jackpot_paid,
          'requestedWin', v_jackpot_paid,
          'jackpotCampaignPayout', true,
          'ledgerSource', 'jackpot_spin_mirror'
        ),
        v_deployment_mode,
        v_effective_device_status,
        v_counts_toward_global
      );
    end if;
  end if;
end;
$$;

create or replace function public.close_accounting_day(p_ref_ts timestamp with time zone default now())
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_business_date date := ((coalesce(p_ref_ts, now()) at time zone 'Asia/Manila'))::date;
  v_now timestamptz := coalesce(p_ref_ts, now());
  v_existing public.accounting_daily_closures%rowtype;
  v_device_rows integer := 0;
  v_total_devices integer := 0;
  v_total_balance numeric := 0;
  v_total_coins_in numeric := 0;
  v_total_hopper_in numeric := 0;
  v_total_hopper_out numeric := 0;
  v_total_bet numeric := 0;
  v_total_win numeric := 0;
  v_total_withdraw numeric := 0;
  v_total_spins bigint := 0;
  v_total_house_take numeric := 0;
  v_total_arcade_amount numeric := 0;
  v_transferred_device_balance numeric := 0;
  v_transferred_happy_pool numeric := 0;
  v_transferred_jackpot_pool numeric := 0;
  v_carried_happy_pool_reserved numeric := 0;
  v_carried_jackpot_pool_reserved numeric := 0;
  v_carried_device_happy_override_reserved numeric := 0;
  v_house_take_after_close numeric := 0;
  v_rtp_percent numeric := 0;
  v_house_edge_percent numeric := 0;
  v_runtime public.casino_runtime%rowtype;
  v_has_open_happy boolean := false;
  v_has_open_jackpot boolean := false;
begin
  if not pg_try_advisory_xact_lock(hashtext('public.close_accounting_day'), hashtext(v_business_date::text)) then
    return jsonb_build_object('closed', false, 'reason', 'already_running');
  end if;

  select *
  into v_existing
  from public.accounting_daily_closures c
  where c.business_date = v_business_date;

  if found then
    return jsonb_build_object(
      'closed', false,
      'reason', 'already_closed',
      'business_date', v_business_date,
      'closed_at', v_existing.closed_at
    );
  end if;

  insert into public.accounting_daily_device_closures (
    business_date,
    device_id,
    device_name,
    deployment_mode,
    balance,
    coins_in_total,
    hopper_in_total,
    hopper_out_total,
    hopper_balance,
    bet_total,
    win_total,
    withdraw_total,
    spins_total,
    house_take_total,
    arcade_total,
    arcade_credit,
    arcade_time_ms,
    transferred_balance_to_house_take,
    house_take_after_close,
    closed_at,
    metadata
  )
  select
    v_business_date,
    d.device_id,
    d.name,
    d.deployment_mode,
    coalesce(t.eligible_balance, 0::numeric) as balance,
    coalesce(t.eligible_coins_in_total, 0::numeric) as coins_in_total,
    coalesce(t.eligible_hopper_in_total, 0::numeric) as hopper_in_total,
    coalesce(t.eligible_hopper_out_total, 0::numeric) as hopper_out_total,
    coalesce(t.eligible_hopper_balance, 0::numeric) as hopper_balance,
    coalesce(t.eligible_bet_total, 0::numeric) as bet_total,
    coalesce(t.eligible_win_total, 0::numeric) as win_total,
    coalesce(t.eligible_withdraw_total, 0::numeric) as withdraw_total,
    coalesce(t.eligible_spins_total, 0::bigint) as spins_total,
    coalesce(t.eligible_house_take_total, 0::numeric) as house_take_total,
    coalesce(t.eligible_arcade_total, 0::numeric) as arcade_total,
    coalesce(t.eligible_arcade_credit, 0)::integer as arcade_credit,
    coalesce(t.eligible_arcade_time_ms, 0)::bigint as arcade_time_ms,
    coalesce(t.eligible_balance, 0::numeric) as transferred_balance_to_house_take,
    coalesce(t.eligible_house_take_total, 0::numeric) + coalesce(t.eligible_balance, 0::numeric) as house_take_after_close,
    v_now,
    jsonb_build_object(
      'eligible_snapshot', true,
      'source_view', 'device_accounting_totals'
    )
  from public.devices d
  left join public.device_accounting_totals t on t.device_id = d.device_id
  where trim(coalesce(d.device_id, '')) <> '';

  get diagnostics v_device_rows = row_count;

  select
    count(*)::integer,
    coalesce(sum(c.balance), 0::numeric),
    coalesce(sum(c.coins_in_total), 0::numeric),
    coalesce(sum(c.hopper_in_total), 0::numeric),
    coalesce(sum(c.hopper_out_total), 0::numeric),
    coalesce(sum(c.bet_total), 0::numeric),
    coalesce(sum(c.win_total), 0::numeric),
    coalesce(sum(c.withdraw_total), 0::numeric),
    coalesce(sum(c.spins_total), 0::bigint),
    coalesce(sum(c.house_take_total), 0::numeric),
    coalesce(sum(c.arcade_total), 0::numeric),
    coalesce(sum(c.transferred_balance_to_house_take), 0::numeric)
  into
    v_total_devices,
    v_total_balance,
    v_total_coins_in,
    v_total_hopper_in,
    v_total_hopper_out,
    v_total_bet,
    v_total_win,
    v_total_withdraw,
    v_total_spins,
    v_total_house_take,
    v_total_arcade_amount,
    v_transferred_device_balance
  from public.accounting_daily_device_closures c
  where c.business_date = v_business_date;

  select *
  into v_runtime
  from public.casino_runtime r
  where r.id = true
  limit 1;

  select
    coalesce(sum(p.amount_remaining), 0::numeric),
    exists(select 1 from public.happy_hour_pots p where p.status in ('queued', 'active'))
  into v_carried_happy_pool_reserved, v_has_open_happy
  from public.happy_hour_pots p
  where p.status in ('queued', 'active');

  select
    coalesce(sum(p.amount_remaining), 0::numeric),
    exists(select 1 from public.jackpot_pots p where p.status in ('queued', 'processing'))
  into v_carried_jackpot_pool_reserved, v_has_open_jackpot
  from public.jackpot_pots p
  where p.status in ('queued', 'processing');

  select coalesce(sum(o.amount_remaining), 0::numeric)
  into v_carried_device_happy_override_reserved
  from public.device_happy_hour_overrides o
  where o.status = 'active'
    and o.amount_remaining > 0;

  v_transferred_happy_pool :=
    greatest(coalesce(v_runtime.happy_hour_prize_balance, 0::numeric) - v_carried_happy_pool_reserved, 0::numeric);
  v_transferred_jackpot_pool :=
    greatest(coalesce(v_runtime.jackpot_pool_balance, 0::numeric) - v_carried_jackpot_pool_reserved, 0::numeric);

  v_house_take_after_close :=
    v_total_house_take
    + v_transferred_device_balance
    + v_transferred_happy_pool
    + v_transferred_jackpot_pool
    - v_carried_device_happy_override_reserved;

  v_rtp_percent :=
    case when v_total_bet > 0 then round((v_total_win / nullif(v_total_bet, 0::numeric)) * 100.0, 4) else 0::numeric end;
  v_house_edge_percent :=
    case when v_total_bet > 0 then round((v_house_take_after_close / nullif(v_total_bet, 0::numeric)) * 100.0, 4) else 0::numeric end;

  insert into public.accounting_daily_closures (
    business_date,
    timezone,
    closed_at,
    total_devices,
    total_balance,
    total_coins_in,
    total_hopper_in,
    total_hopper_out,
    total_bet,
    total_win,
    total_withdraw,
    total_spins,
    total_house_take,
    total_arcade_amount,
    transferred_device_balance,
    transferred_happy_pool,
    transferred_jackpot_pool,
    carried_happy_pool_reserved,
    carried_jackpot_pool_reserved,
    house_take_after_close,
    rtp_percent,
    house_edge_percent,
    metadata
  )
  values (
    v_business_date,
    'Asia/Manila',
    v_now,
    v_total_devices,
    v_total_balance,
    v_total_coins_in,
    v_total_hopper_in,
    v_total_hopper_out,
    v_total_bet,
    v_total_win,
    v_total_withdraw,
    v_total_spins,
    v_total_house_take,
    v_total_arcade_amount,
    v_transferred_device_balance,
    v_transferred_happy_pool,
    v_transferred_jackpot_pool,
    v_carried_happy_pool_reserved,
    v_carried_jackpot_pool_reserved,
    v_house_take_after_close,
    v_rtp_percent,
    v_house_edge_percent,
    jsonb_build_object(
      'device_rows', v_device_rows,
      'eligible_snapshot', true,
      'runtime_prize_pool_balance', coalesce(v_runtime.prize_pool_balance, 0::numeric),
      'runtime_happy_hour_prize_balance', coalesce(v_runtime.happy_hour_prize_balance, 0::numeric),
      'runtime_jackpot_pool_balance', coalesce(v_runtime.jackpot_pool_balance, 0::numeric),
      'carried_device_happy_override_reserved', v_carried_device_happy_override_reserved
    )
  );

  update public.devices
  set
    balance = 0,
    coins_in_total = 0,
    hopper_balance = 0,
    hopper_in_total = 0,
    hopper_out_total = 0,
    bet_total = 0,
    win_total = 0,
    withdraw_total = 0,
    spins_total = 0,
    prize_pool_contrib_total = 0,
    prize_pool_paid_total = 0,
    arcade_credit = 0,
    arcade_credit_updated_at = v_now,
    arcade_time_ms = 0,
    arcade_time_updated_at = v_now,
    arcade_session_started_at = null,
    arcade_time_last_deducted_at = null,
    arcade_total = 0,
    current_game_id = null,
    current_game_name = null,
    current_game_type = null,
    device_status = 'idle',
    active_session_id = null,
    session_started_at = null,
    session_last_heartbeat = null,
    session_ended_at = null,
    runtime_mode = null,
    is_free_game = false,
    free_spins_left = 0,
    pending_free_spins = 0,
    show_free_spin_intro = false,
    current_spin_id = 0,
    session_metadata = '{}'::jsonb,
    house_take_total = 0,
    last_bet_amount = 0,
    last_bet_at = null,
    jackpot_contrib_total = 0,
    jackpot_win_total = 0,
    updated_at = v_now
  where true;

  if to_regclass('public.arcade_metrics') is not null then
    update public.arcade_metrics
    set arcade_balance = 0,
        updated_at = v_now
    where id = 1;
  end if;

  update public.casino_runtime
  set
    active_mode = case
      when v_has_open_happy then active_mode
      else 'BASE'
    end,
    manual_happy_enabled = manual_happy_enabled,
    auto_happy_enabled = auto_happy_enabled,
    happy_hour_prize_balance = v_carried_happy_pool_reserved,
    jackpot_pool_balance = v_carried_jackpot_pool_reserved,
    happy_pool_spin_counter = case when v_has_open_happy then happy_pool_spin_counter else 0 end,
    jackpot_pool_spin_counter = case when v_has_open_jackpot then jackpot_pool_spin_counter else 0 end,
    happy_pool_goal_anchor_at = case when v_has_open_happy then happy_pool_goal_anchor_at else v_now end,
    jackpot_pool_goal_anchor_at = case when v_has_open_jackpot then jackpot_pool_goal_anchor_at else v_now end,
    updated_at = v_now
  where id = true;

  delete from public.jackpot_payout_queue where completed_at is not null;
  delete from public.happy_hour_pots where status = 'completed';
  delete from public.jackpot_pots where status = 'completed';
  delete from public.device_happy_hour_overrides where status in ('completed', 'cancelled');

  truncate table public.device_metric_events restart identity;
  truncate table public.device_arcade_events restart identity;
  truncate table public.device_daily_stats;

  if to_regclass('public.device_game_sessions') is not null then
    execute 'truncate table public.device_game_sessions restart identity cascade';
  end if;

  if to_regclass('public.over_cap_win_events') is not null then
    execute 'truncate table public.over_cap_win_events restart identity cascade';
  end if;

  if to_regclass('public.device_happy_hour_override_wins') is not null then
    execute 'truncate table public.device_happy_hour_override_wins restart identity cascade';
  end if;

  if to_regclass('public.device_spin_event_dedup') is not null then
    execute 'truncate table public.device_spin_event_dedup restart identity cascade';
  end if;

  perform public.recompute_casino_mode();

  return jsonb_build_object(
    'closed', true,
    'business_date', v_business_date,
    'closed_at', v_now,
    'total_devices', v_total_devices,
    'transferred_device_balance', v_transferred_device_balance,
    'transferred_happy_pool', v_transferred_happy_pool,
    'transferred_jackpot_pool', v_transferred_jackpot_pool,
    'carried_device_happy_override_reserved', v_carried_device_happy_override_reserved,
    'house_take_after_close', v_house_take_after_close
  );
end;
$$;

create or replace function public.reset_device_maintenance_runtime(p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_device_id text := trim(coalesce(p_device_id, ''));
    v_deleted_metric_events integer := 0;
    v_deleted_arcade_events integer := 0;
    v_deleted_daily_rows integer := 0;
    v_deleted_ledger_rows integer := 0;
    v_deleted_game_sessions integer := 0;
    v_deleted_spin_dedup_rows integer := 0;
    v_deleted_admin_ledger_rows integer := 0;
    v_deleted_queue_rows integer := 0;
    v_deleted_plan_step_rows integer := 0;
    v_deleted_happy_override_rows integer := 0;
    v_deleted_happy_override_win_rows integer := 0;
    v_jackpot_pot_ids bigint[] := array[]::bigint[];
    v_jackpot_campaign_ids uuid[] := array[]::uuid[];
begin
    if v_device_id = '' then
        raise exception 'p_device_id is required';
    end if;

    if not exists (
        select 1
        from public.devices d
        where d.device_id = v_device_id
        for update
    ) then
        raise exception 'device not found: %', v_device_id;
    end if;

    select coalesce(array_agg(distinct q.jackpot_pot_id) filter (where q.jackpot_pot_id is not null), array[]::bigint[]),
           coalesce(array_agg(distinct q.campaign_id) filter (where q.campaign_id is not null), array[]::uuid[])
    into v_jackpot_pot_ids, v_jackpot_campaign_ids
    from public.jackpot_payout_queue q
    where q.device_id = v_device_id;

    delete from public.jackpot_payout_plan_steps
    where device_id = v_device_id;
    get diagnostics v_deleted_plan_step_rows = row_count;

    delete from public.jackpot_payout_queue
    where device_id = v_device_id;
    get diagnostics v_deleted_queue_rows = row_count;

    delete from public.device_metric_events
    where device_id = v_device_id;
    get diagnostics v_deleted_metric_events = row_count;

    delete from public.device_arcade_events
    where device_id = v_device_id;
    get diagnostics v_deleted_arcade_events = row_count;

    delete from public.device_daily_stats
    where device_id = v_device_id;
    get diagnostics v_deleted_daily_rows = row_count;

    delete from public.device_ledger
    where device_id = v_device_id;
    get diagnostics v_deleted_ledger_rows = row_count;

    delete from public.device_game_sessions
    where device_id = v_device_id;
    get diagnostics v_deleted_game_sessions = row_count;

    delete from public.device_spin_event_dedup
    where device_id = v_device_id;
    get diagnostics v_deleted_spin_dedup_rows = row_count;

    delete from public.device_admin_ledger_entries
    where device_id = v_device_id;
    get diagnostics v_deleted_admin_ledger_rows = row_count;

    delete from public.device_happy_hour_override_wins
    where device_id = v_device_id;
    get diagnostics v_deleted_happy_override_win_rows = row_count;

    delete from public.device_happy_hour_overrides
    where device_id = v_device_id;
    get diagnostics v_deleted_happy_override_rows = row_count;

    update public.devices
    set balance = 0,
        coins_in_total = 0,
        hopper_balance = 0,
        hopper_in_total = 0,
        hopper_out_total = 0,
        bet_total = 0,
        win_total = 0,
        withdraw_total = 0,
        spins_total = 0,
        prize_pool_contrib_total = 0,
        prize_pool_paid_total = 0,
        house_take_total = 0,
        jackpot_contrib_total = 0,
        jackpot_win_total = 0,
        arcade_total = 0,
        arcade_credit = 0,
        arcade_credit_updated_at = null,
        arcade_time_ms = 0,
        arcade_time_updated_at = null,
        arcade_session_started_at = null,
        arcade_time_last_deducted_at = null,
        current_game_id = null,
        current_game_name = null,
        current_game_type = null,
        device_status = 'idle',
        active_session_id = null,
        session_started_at = null,
        session_last_heartbeat = null,
        session_ended_at = null,
        runtime_mode = null,
        is_free_game = false,
        free_spins_left = 0,
        pending_free_spins = 0,
        show_free_spin_intro = false,
        current_spin_id = 0,
        session_metadata = '{}'::jsonb,
        last_bet_amount = 0,
        last_bet_at = null,
        updated_at = now()
    where device_id = v_device_id;

    update public.casino_runtime
    set jackpot_pending_payout = false,
        active_jackpot_pot_id = null,
        updated_at = now()
    where active_jackpot_pot_id = any(v_jackpot_pot_ids)
       or (
            cardinality(v_jackpot_campaign_ids) > 0
            and active_jackpot_pot_id in (
                select jp.id
                from public.jackpot_pots jp
                where jp.campaign_id = any(v_jackpot_campaign_ids)
            )
        );

    return jsonb_build_object(
        'ok', true,
        'device_id', v_device_id,
        'deleted_plan_step_rows', v_deleted_plan_step_rows,
        'deleted_queue_rows', v_deleted_queue_rows,
        'deleted_metric_events', v_deleted_metric_events,
        'deleted_arcade_events', v_deleted_arcade_events,
        'deleted_daily_rows', v_deleted_daily_rows,
        'deleted_ledger_rows', v_deleted_ledger_rows,
        'deleted_game_sessions', v_deleted_game_sessions,
        'deleted_spin_dedup_rows', v_deleted_spin_dedup_rows,
        'deleted_admin_ledger_rows', v_deleted_admin_ledger_rows,
        'deleted_happy_override_win_rows', v_deleted_happy_override_win_rows,
        'deleted_happy_override_rows', v_deleted_happy_override_rows,
        'reset_all_stats', true
    );
end;
$$;

create or replace view public.devices_dashboard_live as
 select d.id,
    d.device_id,
    d.name,
    d.created_at,
    d.updated_at,
    (
        case
            when (d.deployment_mode = 'online'::text) then greatest(0::numeric, coalesce(t.eligible_balance, 0::numeric))
            else d.balance
        end)::numeric(14,2) as balance,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_coins_in_total, 0::numeric)
        else d.coins_in_total
    end as coins_in_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_hopper_balance, 0::numeric)
        else d.hopper_balance
    end as hopper_balance,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_hopper_in_total, 0::numeric)
        else d.hopper_in_total
    end as hopper_in_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_hopper_out_total, 0::numeric)
        else d.hopper_out_total
    end as hopper_out_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_bet_total, 0::numeric)
        else d.bet_total
    end as bet_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_win_total, 0::numeric)
        else d.win_total
    end as win_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_withdraw_total, 0::numeric)
        else d.withdraw_total
    end as withdraw_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_spins_total, 0::bigint)
        else d.spins_total
    end as spins_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_prize_pool_contrib_total, 0::numeric)
        else d.prize_pool_contrib_total
    end as prize_pool_contrib_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_prize_pool_paid_total, 0::numeric)
        else d.prize_pool_paid_total
    end as prize_pool_paid_total,
    d.current_game_id,
    d.current_game_name,
    case
        when ((d.last_seen_at is null) or (d.last_seen_at < (now() - '00:01:30'::interval))) then 'offline'::text
        else d.device_status
    end as device_status,
    d.active_session_id,
    d.session_started_at,
    d.session_last_heartbeat,
    d.session_ended_at,
    d.runtime_mode,
    d.is_free_game,
    d.free_spins_left,
    d.pending_free_spins,
    d.show_free_spin_intro,
    d.current_spin_id,
    d.session_metadata,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_house_take_total, 0::numeric)
        else d.house_take_total
    end as house_take_total,
    d.last_bet_amount,
    d.last_bet_at,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_jackpot_contrib_total, 0::numeric)
        else d.jackpot_contrib_total
    end as jackpot_contrib_total,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_jackpot_win_total, 0::numeric)
        else d.jackpot_win_total
    end as jackpot_win_total,
    d.arcade_shell_version,
    d.current_ip,
    coalesce(j.has_active, false) as jackpot_selected,
    coalesce(j.target_amount, 0::numeric) as jackpot_target_amount,
    coalesce(j.remaining_amount, 0::numeric) as jackpot_remaining_amount,
    coalesce(j.spins_until_start, 0) as jackpot_spins_until_start,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_arcade_total, 0::numeric)
        else d.arcade_total
    end as arcade_total,
    d.deployment_mode,
    d.current_game_type,
    d.last_seen_at,
    d.last_activity_at,
    d.withdraw_enabled,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_arcade_credit, 0)
        else d.arcade_credit
    end as arcade_credit,
    d.arcade_credit_updated_at,
    case
        when (d.deployment_mode = 'online'::text) then coalesce(t.eligible_arcade_time_ms, 0::bigint)
        else d.arcade_time_ms
    end as arcade_time_ms,
    d.arcade_time_updated_at,
    d.arcade_session_started_at,
    d.arcade_time_last_deducted_at,
    coalesce(t.eligible_balance, 0::numeric) as eligible_balance,
    coalesce(t.eligible_coins_in_total, 0::numeric) as eligible_coins_in_total,
    coalesce(t.eligible_hopper_balance, 0::numeric) as eligible_hopper_balance,
    coalesce(t.eligible_hopper_in_total, 0::numeric) as eligible_hopper_in_total,
    coalesce(t.eligible_hopper_out_total, 0::numeric) as eligible_hopper_out_total,
    coalesce(t.eligible_bet_total, 0::numeric) as eligible_bet_total,
    coalesce(t.eligible_win_total, 0::numeric) as eligible_win_total,
    coalesce(t.eligible_withdraw_total, 0::numeric) as eligible_withdraw_total,
    coalesce(t.eligible_spins_total, 0::bigint) as eligible_spins_total,
    coalesce(t.eligible_prize_pool_contrib_total, 0::numeric) as eligible_prize_pool_contrib_total,
    coalesce(t.eligible_prize_pool_paid_total, 0::numeric) as eligible_prize_pool_paid_total,
    coalesce(t.eligible_house_take_total, 0::numeric) as eligible_house_take_total,
    coalesce(t.eligible_jackpot_contrib_total, 0::numeric) as eligible_jackpot_contrib_total,
    coalesce(t.eligible_jackpot_win_total, 0::numeric) as eligible_jackpot_win_total,
    coalesce(t.eligible_arcade_total, 0::numeric) as eligible_arcade_total,
    coalesce(t.eligible_arcade_credit, 0) as eligible_arcade_credit,
    coalesce(t.eligible_arcade_time_ms, 0::bigint) as eligible_arcade_time_ms,
    d.balance as all_balance,
    d.coins_in_total as all_coins_in_total,
    d.hopper_balance as all_hopper_balance,
    d.hopper_in_total as all_hopper_in_total,
    d.hopper_out_total as all_hopper_out_total,
    d.bet_total as all_bet_total,
    d.win_total as all_win_total,
    d.withdraw_total as all_withdraw_total,
    d.spins_total as all_spins_total,
    d.prize_pool_contrib_total as all_prize_pool_contrib_total,
    d.prize_pool_paid_total as all_prize_pool_paid_total,
    d.house_take_total as all_house_take_total,
    d.jackpot_contrib_total as all_jackpot_contrib_total,
    d.jackpot_win_total as all_jackpot_win_total,
    d.arcade_total as all_arcade_total,
    d.arcade_credit as all_arcade_credit,
    d.arcade_time_ms as all_arcade_time_ms,
    coalesce(ho.has_active, false) as happy_override_selected,
    coalesce(ho.target_amount, 0::numeric) as happy_override_target_amount,
    coalesce(ho.remaining_amount, 0::numeric) as happy_override_remaining_amount,
    ho.override_id as happy_override_id
   from (((public.devices d
     left join ( select q.device_id,
            true as has_active,
            sum(q.target_amount) as target_amount,
            sum(q.remaining_amount) as remaining_amount,
            min(q.spins_until_start) as spins_until_start
           from public.jackpot_payout_queue q
          where (q.completed_at is null)
          group by q.device_id) j on ((j.device_id = d.device_id)))
     left join ( select o.device_id,
            true as has_active,
            max(o.id) as override_id,
            sum(o.amount_total) as target_amount,
            sum(o.amount_remaining) as remaining_amount
           from public.device_happy_hour_overrides o
          where ((o.status = 'active'::text) and (o.amount_remaining > 0::numeric))
          group by o.device_id) ho on ((ho.device_id = d.device_id)))
     left join public.device_accounting_totals t on ((t.device_id = d.device_id)));

create or replace view public.global_stats_live as
 with totals as (
         select coalesce(sum(d.balance), 0::numeric) as total_balance,
            coalesce(sum(d.coins_in_total), 0::numeric) as total_coins_in,
            coalesce(sum(d.hopper_balance), 0::numeric) as total_hopper,
            coalesce(sum(d.bet_total), 0::numeric) as total_bet_amount,
            coalesce(sum(d.win_total), 0::numeric) as total_win_amount,
            coalesce(sum(d.withdraw_total), 0::numeric) as total_withdraw_amount,
            ( select count(*) as count
                   from public.device_metric_events e
                  where ((e.event_type = 'spin'::text) and (e.counts_toward_global = true))) as total_spins,
            coalesce(sum(d.house_take_total), 0::numeric) as total_house_take,
            coalesce(sum(d.jackpot_contrib_total), 0::numeric) as total_jackpot_contrib,
            coalesce(sum(d.jackpot_win_total), 0::numeric) as total_jackpot_win
           from public.devices_dashboard_live d
          where (coalesce(nullif(trim(both from d.deployment_mode), ''::text), 'online'::text) = 'online'::text)
        ), eligible_devices as (
         select count(*) as device_count
           from public.devices d
          where (coalesce(nullif(trim(both from d.deployment_mode), ''::text), 'online'::text) = 'online'::text)
        ), runtime as (
         select coalesce(r.prize_pool_balance, 0::numeric) as prize_pool_balance,
            coalesce(r.happy_hour_prize_balance, 0::numeric) as happy_hour_prize_balance,
            coalesce(r.jackpot_pool_balance, 0::numeric) as jackpot_pool_balance
           from public.casino_runtime r
          where (r.id = true)
         limit 1
        ), liabilities as (
         select coalesce(( select sum(hp.amount_remaining) as sum
                   from public.happy_hour_pots hp
                  where (hp.status = 'queued'::text)), 0::numeric) as happy_queued_amount,
            coalesce(( select sum(jp.amount_remaining) as sum
                   from public.jackpot_pots jp
                  where (jp.status = 'queued'::text)), 0::numeric) as jackpot_queued_amount,
            coalesce(( select sum(jp.amount_remaining) as sum
                   from public.jackpot_pots jp
                  where (jp.status = 'processing'::text)), 0::numeric) as jackpot_processing_amount,
            coalesce(( select sum(o.amount_remaining) as sum
                   from public.device_happy_hour_overrides o
                  where ((o.status = 'active'::text) and (o.amount_remaining > 0::numeric))), 0::numeric) as device_happy_override_amount
        ), arcade as (
         select coalesce(sum(e.amount), 0::numeric) as total_arcade_amount
           from public.device_arcade_events e
          where e.counts_toward_global
        )
 select t.total_balance,
    t.total_coins_in,
    t.total_hopper,
    t.total_bet_amount,
    t.total_win_amount,
    t.total_withdraw_amount,
    t.total_spins,
    case
        when (t.total_bet_amount > 0::numeric) then round(((t.total_win_amount / nullif(t.total_bet_amount, 0::numeric)) * 100.0), 4)
        else 0::numeric
    end as global_rtp_percent,
    ed.device_count,
    now() as generated_at,
    t.total_house_take,
    case
        when (t.total_bet_amount > 0::numeric) then round(((t.total_house_take / nullif(t.total_bet_amount, 0::numeric)) * 100.0), 4)
        else 0::numeric
    end as global_house_edge_percent,
    t.total_jackpot_contrib,
    t.total_jackpot_win,
    ((t.total_coins_in - t.total_withdraw_amount) - t.total_balance - coalesce(rt.prize_pool_balance, 0::numeric) - coalesce(rt.happy_hour_prize_balance, 0::numeric) - coalesce(rt.jackpot_pool_balance, 0::numeric) - coalesce(lb.happy_queued_amount, 0::numeric) - coalesce(lb.jackpot_queued_amount, 0::numeric) - coalesce(lb.jackpot_processing_amount, 0::numeric) - coalesce(lb.device_happy_override_amount, 0::numeric)) as total_house_net,
    case
        when (t.total_coins_in > 0::numeric) then round(((((t.total_coins_in - t.total_withdraw_amount) - t.total_balance - coalesce(rt.prize_pool_balance, 0::numeric) - coalesce(rt.happy_hour_prize_balance, 0::numeric) - coalesce(rt.jackpot_pool_balance, 0::numeric) - coalesce(lb.happy_queued_amount, 0::numeric) - coalesce(lb.jackpot_queued_amount, 0::numeric) - coalesce(lb.jackpot_processing_amount, 0::numeric) - coalesce(lb.device_happy_override_amount, 0::numeric)) / nullif(t.total_coins_in, 0::numeric)) * 100.0), 4)
        else 0::numeric
    end as global_house_net_percent,
    coalesce(am.total_arcade_amount, 0::numeric) as total_arcade_amount
   from (((totals t
     cross join eligible_devices ed)
     left join runtime rt on true)
     left join liabilities lb on true)
     left join arcade am on true;

grant all on function public.enqueue_device_happy_hour_override(text, numeric) to anon;
grant all on function public.enqueue_device_happy_hour_override(text, numeric) to authenticated;
grant all on function public.enqueue_device_happy_hour_override(text, numeric) to service_role;

grant all on table public.device_happy_hour_overrides to anon;
grant all on table public.device_happy_hour_overrides to authenticated;
grant all on table public.device_happy_hour_overrides to service_role;
grant all on table public.device_happy_hour_override_wins to anon;
grant all on table public.device_happy_hour_override_wins to authenticated;
grant all on table public.device_happy_hour_override_wins to service_role;

grant all on sequence public.device_happy_hour_overrides_id_seq to anon;
grant all on sequence public.device_happy_hour_overrides_id_seq to authenticated;
grant all on sequence public.device_happy_hour_overrides_id_seq to service_role;
grant all on sequence public.device_happy_hour_override_wins_id_seq to anon;
grant all on sequence public.device_happy_hour_override_wins_id_seq to authenticated;
grant all on sequence public.device_happy_hour_override_wins_id_seq to service_role;
