pcm.usb_audio_hw {
  type hw
  card "Device"
  device 0
}

pcm.usb_audio {
  type plug
  slave.pcm "usb_audio_hw"
}

pcm.!default {
  type plug
  slave.pcm "usb_audio_hw"
}

ctl.!default {
  type hw
  card "Device"
}
